// Code generated by MCHP Chatbot
/*******************************************************************************
  Main Source File

  Company:
    Microchip Technology Inc.

  File Name:
    main.c

  Summary:
    This file contains the "main" function for a project.

  Description:
    This file contains the "main" function for a project.  The
    "main" function calls the "SYS_Initialize" function to initialize the state
    machines of all modules in the system
 *******************************************************************************/

// *****************************************************************************
// *****************************************************************************
// Section: Included Files
// *****************************************************************************
// *****************************************************************************

#include <stddef.h>                     // Defines NULL
#include <stdbool.h>                    // Defines true
#include <stdlib.h>                     // Defines EXIT_FAILURE
#include "definitions.h"                // SYS function prototypes

// *****************************************************************************
// *****************************************************************************
// Section: Local Delay Function
// *****************************************************************************
// *****************************************************************************

// Code generated by MCHP Chatbot
static void delay_ms(uint32_t ms) {
    /* Assuming 48MHz core clock, ~48000 for 1 ms. Adjust as needed. */
    volatile uint32_t count;
    while(ms--) {
        count = 48000/12; // Adjust divider based on optimization & tests
        while(count--) {
            __asm volatile ("nop");
        }
    }
}

// *****************************************************************************
// *****************************************************************************
// Section: Main Entry Point
// *****************************************************************************
// *****************************************************************************

int main ( void )
{
    /* Initialize all modules */
    SYS_Initialize ( NULL );

    while ( true )
    {
        // Toggle LED1 (PA00)
        LED1_Toggle();
        delay_ms(500); // 500ms ON/OFF for 1Hz blink

        SYS_Tasks(); // Maintain Harmony state machines if required
    }

    /* Execution should not come here during normal operation */
    return ( EXIT_FAILURE );
}

/*******************************************************************************
 End of File
*/
